[40기 전민식] ADD: GET Products API 4종류
wecode-bootcamp-korea/40-1st-CodeSecurityGuard-backend pull request #4
Opened 2022-12-09 06:56 UTC by minsicko

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- products 조회 API

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
1. get ALL products
2. get products by category id
3. get products by subcategory id
4. get product by id

<br />

## :: 테스트 결과 이미지
ALL:
![Screen Shot 2022-12-09 at 3 50 09 PM](https://user-images.githubusercontent.com/111173900/206642490-fe9da6fc-2e36-41cf-b2e1-59808655b581.png)

Category id:
![Screen Shot 2022-12-09 at 3 50 44 PM](https://user-images.githubusercontent.com/111173900/206642590-0f38390e-0ff8-4222-859b-59f5caadee60.png)

SubCategory id:
![Screen Shot 2022-12-09 at 3 51 20 PM](https://user-images.githubusercontent.com/111173900/206642677-db32dd8c-787c-412e-b59c-63b16f0e3f1d.png)

Product by id:
![Screen Shot 2022-12-09 at 3 51 46 PM](https://user-images.githubusercontent.com/111173900/206642767-8208624c-38d5-4588-837b-82fd51277399.png)

<br />

### TRELLO
https://trello.com/c/GUlrw2k1

2022-12-11 08:00 UTC, sangwoong03 requested changes

2022-12-11 08:00 UTC, sangwoong03 commented on api/routes/productRouter.js
> +router.get('/all', productController.getAllProducts)
전체 상품 리스트를 조회할 때 `/all`이라는 엔드포인트로 직접 명시하지 않아도 될 것 같아 보입니다!
```suggestion
router.get('/', productController.getAllProducts)
```

2022-12-11 08:00 UTC, sangwoong03 commented on api/models/productDao.js
> +        const result = await dataSource.query(`SELECT * FROM products`)
와일드카드 중 asterisk `*` 기호를 통해 전체 데이터를 조회할 수 있습니다.

하지만 와일드카드를 사용할 때 주의해야 할 점이 있습니다.

- 전체 데이터를 가져오기 때문에 클라이언트가 필요한 정보가 아닌, 관리 목적의 데이터를 반환할 수 있다.
- 필요한 데이터만 조회하는 것이 아니라 모든 데이터를 조회하기 때문에 성능 저하 이슈가 발생할 수 있다.

위 두가지 이유로 `*`로 데이터를 조회하기 보다는 컬럼을 직접 적어주는 것이 좋아보입니다!

필요한 데이터만 반환될 수 있도록 해당 부분은 모두 수정해주세요~!

2022-12-11 08:00 UTC, sangwoong03 commented on api/models/productDao.js
> +        )
쿼리문을 잘 작성해주셨네요!

현재 컬럼명이 snake_case로 되어있는데 프론트 개발자분들과의 협의를 통해 `camelCase` 네이밍을 사용하지 않는 것인가요?

2022-12-11 08:00 UTC, sangwoong03 commented on api/models/productDao.js
> +                *
해당 부분 수정해주세요~!

2022-12-11 08:00 UTC, sangwoong03 commented on api/models/productDao.js
> +            SELECT * FROM products AS p
해당 부분도 수정해주세요~!

2022-12-11 08:54 UTC, minsicko commented on api/models/productDao.js
> +        )
FRONT-END 개발자님들이랑 camelCase 사용하기로 했어요.
snake_case로 response가 간다는걸 생각못했어요. 
alias 추가하겠습니다

2022-12-12 01:03 UTC, sangwoong03 approved these changes
LGTM 👍  고생하셨습니다

2022-12-12 01:03 UTC, merged