[40기 전민식] ADD: feature-ordersApi
wecode-bootcamp-korea/40-1st-CodeSecurityGuard-backend pull request #8
Opened 2022-12-13 03:17 UTC by minsicko

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## 결제 (orders) 테이블
- 결제 페이지가 따로 없기때문에, 프로젝트 진행속도를 올리기 위해 orders table 안에 간단하게 user_id & amount 컬럼만 존재하게 구현했습니다.

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 결제 기능 추가

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- POST /orders 호출 시 orders table에 내용 추가 & 유저 포인트 차감

<br />

## :: 테스트 결과 이미지
1. 로그인 안했을떄
![Screen Shot 2022-12-13 at 12 05 49 PM](https://user-images.githubusercontent.com/111173900/207216484-0a1e647b-a1e0-4d5e-9481-1e2870d97a7c.png)

2. 토큰 사용
![Screen Shot 2022-12-13 at 12 06 29 PM](https://user-images.githubusercontent.com/111173900/207216579-75dc51be-fc8d-494d-8355-43990a9812c6.png)

3. 테이블에 추가
<img width="288" alt="Screen Shot 2022-12-13 at 12 08 30 PM" src="https://user-images.githubusercontent.com/111173900/207216830-37f092f7-82d6-4579-9876-be24af6a05e8.png">

4. 포인트 차감 확인 (9-->0)
![Screen Shot 2022-12-13 at 12 15 20 PM](https://user-images.githubusercontent.com/111173900/207217734-7dbdbd91-61f5-44b0-b238-b08fdcd2e7c6.png)

<br />

## :: TRELLO
https://trello.com/c/xoK4NuGn

2022-12-13 06:56 UTC, sangwoong03 requested changes
민식님!

orders table에 데이터를 추가하고
users table에서 포인트를 차감하는 방식을 구현하기 위해서는 typeorm - transaction을 사용하면 좋을 것 같습니다!
다음과 같은 상황이 발생할 수 있기 때문입니다!
`orders 테이블에 데이터는 추가가 되었지만 유저의 포인트가 가격을 넘는 경우,,,`
주문 정보는 생겼지만 point가 차감되지 않을 수 있습니다.

영석님께도 전달드렸는데 같이 공부해보시고 적용하면 좋을 것 같아요
https://orkhan.gitbook.io/typeorm/docs/transactions
프로세스는 다음과 같습니다!

`orderDao.js` 파일 내부에 `createOrder()` 함수가 있다는 가정하에...
1.  orders table에 데이터를 추가한다
2. users table에서 price만큼 포인트를 차감한다.
3. users 테이블에서 차감된 포인트를 조회한다.

하나의 함수 안에서 작성하도록 구현할 수 있습니다.

2022-12-13 08:07 UTC, minsicko commented
2번 유저가 포인트 차감 안될때
![Screen Shot 2022-12-13 at 5 05 49 PM](https://user-images.githubusercontent.com/111173900/207260194-1fceeb21-0e8b-4aef-9547-3ca56fd0e1c9.png)

3번 유저 1포인트 차감
![Screen Shot 2022-12-13 at 5 06 53 PM](https://user-images.githubusercontent.com/111173900/207260376-02b46795-7d77-43c4-871a-8c89dc39af31.png)

2022-12-14 01:14 UTC, sangwoong03 commented on api/models/orderDao.js
> +           throw err
예외 처리를 할 때 어떤 에러인지 반환하면 좋을 것 같네요

`CANNOT_MAKE_ORDER` 혹은 `INSUFFICIENT_POINT` 로 클라이언트에게 에러처리를 해주면 좋을 것 같습니다.

2022-12-14 01:15 UTC, sangwoong03 commented on api/models/orderDao.js
> +    }
여기서 발생하는 에러는 orders 테이블에 특정 정보를 넣을 때도 발생할 수 있으니 다른 에러 처리를 해주면 좋을 것 같습니다!

2022-12-14 02:19 UTC, minsicko commented
1. POINT 부족
![Screen Shot 2022-12-14 at 11 18 09 AM](https://user-images.githubusercontent.com/111173900/207489097-93359a81-0ba9-42ca-9a6c-a792f8565a28.png)

2. 다른 에러 (query typo)
![Screen Shot 2022-12-14 at 11 18 50 AM](https://user-images.githubusercontent.com/111173900/207489168-0f6502eb-5a74-4185-9d00-64a83cb64409.png)

2022-12-14 06:30 UTC, sangwoong03 approved these changes
LGTM 👍

2022-12-14 06:30 UTC, merged